# https://github.com/CocoaPods/pod-template/blob/master/.travis.yml

language: objective-c
osx_image: xcode8.2

cache:
  - cocoapods

before_install:
  - gem install cocoapods
  - pod install --project-directory=test/proj.ios_mac

script:
  - xcodebuild -workspace test/ee_x_test.xcworkspace -scheme ee_x_test_mobile -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO